### ISSUE TITLE
Clicking links opens in the electron apps with no way to return

### ISSUE THREAD

**Issue by flexiondotorg** [ryanleesipes/snapcraft-forum#1]
If you click a link within Discourse that link opens directly in the Electron application, with no way to return to Discourse. Perhaps links outside of the base FQDN of the Discourse instance should be opened in a browser?

**Comment by ryanleesipes** [comment]
Yeah, let me see how I can address that.

**Comment by ryanleesipes** [comment]
Newest commits should fix this, seems to work properly in my tests. Going to upload to snapcraft soon.

**Comment by ryanleesipes** [comment]
Well @flexiondotorg , it appears as though I overlooked something in testing, and that is Snap confinement. My snap needs the ability to open applications within a new window on the user's browser, however that is currently not possible given the default strict confinement. I will have to look into how to allow permissions for the snap (in electron builder), in order to make this work properly.

**Comment by ryanleesipes** [comment]
Default plugs are being used:
- browser-support
- gsettings
- home
- network
- opengl
- pulseaudio
- unity7
- x11

I'm not sure what needs to be added in order for it to pass along links to the browser, and I'm too stubborn to put it into classic mode. Help welcome.

**Comment by ogra1** [comment]
to make it work in a snap something like:

require('child_process')
child_process.execSync('xdg-open' + url)

should work... you should not need any special interfaces for this ...

**Comment by ryanleesipes** [comment]
It doesn't work when snapd-xdg-open is not installed (like on elementary OS). 

It looks like there are some ideas for how to solve this in the forum. @ogra1 @flexiondotorg would appreciate your help moving this along: https://forum.snapcraft.io/t/integrate-snapd-xdg-open-into-snapd-repository
